version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
      image: wurstmeister/kafka:0.10.0.0
      hostname: kafka
      container_name: kafka
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: "9092"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "dockertest:3:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  tokenserver:
      image: tokenserver
      hostname: tokenserver
      container_name: tokenserver
      tty: true
      ports:
        - "8888:8888"
      depends_on:
        - zookeeper
        - kafka
  producer1:
        image: producer
        hostname: producer1
        container_name: producer1
        tty: true
        depends_on:
          - zookeeper
          - kafka
          - tokenserver
  producer2:
          image: producer
          hostname: producer2
          container_name: producer2
          tty: true
          depends_on:
            - zookeeper
            - kafka
            - tokenserver
  producer3:
            image: producer
            hostname: producer3
            container_name: producer3
            tty: true
            depends_on:
              - zookeeper
              - kafka
              - tokenserver
  consumer1:
          image: consumer
          hostname: consumer1
          container_name: consumer1
          tty: true
          depends_on:
            - zookeeper
            - kafka
            - tokenserver
  consumer2:
            image: consumer
            hostname: consumer2
            container_name: consumer2
            tty: true
            depends_on:
              - zookeeper
              - kafka
              - tokenserver
  consumer3:
              image: consumer
              hostname: consumer3
              container_name: consumer3
              tty: true
              depends_on:
                - zookeeper
                - kafka
                - tokenserver