version: "2"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
      image: wurstmeister/kafka:0.10.0.0
      hostname: kafka
      container_name: kafka
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: "9092"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "dockertest:1:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  tokenserver:
      image: tokenserver
      hostname: tokenserver
      container_name: tokenserver
      tty: true
      ports:
        - "8888:8888"
      depends_on:
        - zookeeper
        - kafka
  producer:
        image: producer
        hostname: producer
        container_name: producer
        tty: true
        depends_on:
          - zookeeper
          - kafka
          - tokenserver
  consumer:
          image: consumer
          hostname: consumer
          container_name: consumer
          tty: true
          depends_on:
            - zookeeper
            - kafka
            - tokenserver
