version: "3"
services:
  zookeeper:
    image: confluent/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
      image: confluent/kafka:latest
      hostname: kafka
      container_name: kafka
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: "9092"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_BROKER_ID: 1
        KAFKA_auto_create_topics_enable: "true"
        KAFKA_num_partitions: 1
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
  schemaregistry:
      image: confluent/schema-registry
      hostname: schemaregistry
      container_name: schemaregistry
      depends_on:
        - kafka
        - zookeeper
      ports:
        - "8081:8081"
      environment:
        SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
        SR_KAFKASTORE_TOPIC: "_schemas"
  string_producer:
        image: string_producer
        hostname: string_producer
        container_name: string_producer
        tty: true
        depends_on:
          - zookeeper
          - kafka
  string_avro_converter:
          image: string_avro_converter
          hostname: string_avro_converter
          container_name: string_avro_converter
          tty: true
          depends_on:
            - zookeeper
            - kafka
            - schemaregistry
  avro_consumer:
          image: avro_consumer
          hostname: avro_consumer
          container_name: avro_consumer
          tty: true
          depends_on:
            - zookeeper
            - kafka
            - schemaregistry